// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: splitandgo/v1/chunk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_StreamUpload_FullMethodName   = "/splitandgo.v1.StreamService/StreamUpload"
	StreamService_StreamDownload_FullMethodName = "/splitandgo.v1.StreamService/StreamDownload"
	StreamService_StreamBidi_FullMethodName     = "/splitandgo.v1.StreamService/StreamBidi"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	// StreamUpload receives a stream of chunks from the client
	StreamUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkEnvelope, StreamAck], error)
	// StreamDownload sends a stream of chunks to the client
	StreamDownload(ctx context.Context, in *StreamDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkEnvelope], error)
	// StreamBidi enables bidirectional chunk streaming
	StreamBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkEnvelope, ChunkEnvelope], error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) StreamUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkEnvelope, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_StreamUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkEnvelope, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamUploadClient = grpc.ClientStreamingClient[ChunkEnvelope, StreamAck]

func (c *streamServiceClient) StreamDownload(ctx context.Context, in *StreamDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_StreamDownload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDownloadRequest, ChunkEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamDownloadClient = grpc.ServerStreamingClient[ChunkEnvelope]

func (c *streamServiceClient) StreamBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkEnvelope, ChunkEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[2], StreamService_StreamBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkEnvelope, ChunkEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamBidiClient = grpc.BidiStreamingClient[ChunkEnvelope, ChunkEnvelope]

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
type StreamServiceServer interface {
	// StreamUpload receives a stream of chunks from the client
	StreamUpload(grpc.ClientStreamingServer[ChunkEnvelope, StreamAck]) error
	// StreamDownload sends a stream of chunks to the client
	StreamDownload(*StreamDownloadRequest, grpc.ServerStreamingServer[ChunkEnvelope]) error
	// StreamBidi enables bidirectional chunk streaming
	StreamBidi(grpc.BidiStreamingServer[ChunkEnvelope, ChunkEnvelope]) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) StreamUpload(grpc.ClientStreamingServer[ChunkEnvelope, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamUpload not implemented")
}
func (UnimplementedStreamServiceServer) StreamDownload(*StreamDownloadRequest, grpc.ServerStreamingServer[ChunkEnvelope]) error {
	return status.Error(codes.Unimplemented, "method StreamDownload not implemented")
}
func (UnimplementedStreamServiceServer) StreamBidi(grpc.BidiStreamingServer[ChunkEnvelope, ChunkEnvelope]) error {
	return status.Error(codes.Unimplemented, "method StreamBidi not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_StreamUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).StreamUpload(&grpc.GenericServerStream[ChunkEnvelope, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamUploadServer = grpc.ClientStreamingServer[ChunkEnvelope, StreamAck]

func _StreamService_StreamDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamDownload(m, &grpc.GenericServerStream[StreamDownloadRequest, ChunkEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamDownloadServer = grpc.ServerStreamingServer[ChunkEnvelope]

func _StreamService_StreamBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).StreamBidi(&grpc.GenericServerStream[ChunkEnvelope, ChunkEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamBidiServer = grpc.BidiStreamingServer[ChunkEnvelope, ChunkEnvelope]

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "splitandgo.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpload",
			Handler:       _StreamService_StreamUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDownload",
			Handler:       _StreamService_StreamDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBidi",
			Handler:       _StreamService_StreamBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "splitandgo/v1/chunk.proto",
}
