// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: splitandgo/v1/chunk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChecksumType int32

const (
	ChecksumType_CHECKSUM_TYPE_UNSPECIFIED ChecksumType = 0
	ChecksumType_CHECKSUM_TYPE_NONE        ChecksumType = 1
	ChecksumType_CHECKSUM_TYPE_CRC32       ChecksumType = 2
	ChecksumType_CHECKSUM_TYPE_SHA256      ChecksumType = 3
)

// Enum value maps for ChecksumType.
var (
	ChecksumType_name = map[int32]string{
		0: "CHECKSUM_TYPE_UNSPECIFIED",
		1: "CHECKSUM_TYPE_NONE",
		2: "CHECKSUM_TYPE_CRC32",
		3: "CHECKSUM_TYPE_SHA256",
	}
	ChecksumType_value = map[string]int32{
		"CHECKSUM_TYPE_UNSPECIFIED": 0,
		"CHECKSUM_TYPE_NONE":        1,
		"CHECKSUM_TYPE_CRC32":       2,
		"CHECKSUM_TYPE_SHA256":      3,
	}
)

func (x ChecksumType) Enum() *ChecksumType {
	p := new(ChecksumType)
	*p = x
	return p
}

func (x ChecksumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChecksumType) Descriptor() protoreflect.EnumDescriptor {
	return file_splitandgo_v1_chunk_proto_enumTypes[0].Descriptor()
}

func (ChecksumType) Type() protoreflect.EnumType {
	return &file_splitandgo_v1_chunk_proto_enumTypes[0]
}

func (x ChecksumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChecksumType.Descriptor instead.
func (ChecksumType) EnumDescriptor() ([]byte, []int) {
	return file_splitandgo_v1_chunk_proto_rawDescGZIP(), []int{0}
}

type ChunkEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      uint32                 `protobuf:"varint,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ChecksumBytes []byte                 `protobuf:"bytes,8,opt,name=checksum_bytes,json=checksumBytes,proto3" json:"checksum_bytes,omitempty"`
	ChecksumType  ChecksumType           `protobuf:"varint,9,opt,name=checksum_type,json=checksumType,proto3,enum=splitandgo.v1.ChecksumType" json:"checksum_type,omitempty"`
	IsLast        bool                   `protobuf:"varint,10,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	IsCompressed  bool                   `protobuf:"varint,11,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkEnvelope) Reset() {
	*x = ChunkEnvelope{}
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkEnvelope) ProtoMessage() {}

func (x *ChunkEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkEnvelope.ProtoReflect.Descriptor instead.
func (*ChunkEnvelope) Descriptor() ([]byte, []int) {
	return file_splitandgo_v1_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChunkEnvelope) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChunkEnvelope) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkEnvelope) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChunkEnvelope) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ChunkEnvelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkEnvelope) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *ChunkEnvelope) GetChecksumBytes() []byte {
	if x != nil {
		return x.ChecksumBytes
	}
	return nil
}

func (x *ChunkEnvelope) GetChecksumType() ChecksumType {
	if x != nil {
		return x.ChecksumType
	}
	return ChecksumType_CHECKSUM_TYPE_UNSPECIFIED
}

func (x *ChunkEnvelope) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *ChunkEnvelope) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *ChunkEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunksReceived int64                  `protobuf:"varint,2,opt,name=chunks_received,json=chunksReceived,proto3" json:"chunks_received,omitempty"`
	BytesReceived  int64                  `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_splitandgo_v1_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamAck) GetChunksReceived() int64 {
	if x != nil {
		return x.ChunksReceived
	}
	return 0
}

func (x *StreamAck) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *StreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StreamDownloadRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceId         string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	PreferredChunkSize int32                  `protobuf:"varint,2,opt,name=preferred_chunk_size,json=preferredChunkSize,proto3" json:"preferred_chunk_size,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamDownloadRequest) Reset() {
	*x = StreamDownloadRequest{}
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadRequest) ProtoMessage() {}

func (x *StreamDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_splitandgo_v1_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadRequest.ProtoReflect.Descriptor instead.
func (*StreamDownloadRequest) Descriptor() ([]byte, []int) {
	return file_splitandgo_v1_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDownloadRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *StreamDownloadRequest) GetPreferredChunkSize() int32 {
	if x != nil {
		return x.PreferredChunkSize
	}
	return 0
}

func (x *StreamDownloadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_splitandgo_v1_chunk_proto protoreflect.FileDescriptor

const file_splitandgo_v1_chunk_proto_rawDesc = "" +
	"\n" +
	"\x19splitandgo/v1/chunk.proto\x12\rsplitandgo.v1\"\x82\x04\n" +
	"\rChunkEnvelope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x03R\vtotalChunks\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\rR\bchecksum\x12%\n" +
	"\x0echecksum_bytes\x18\b \x01(\fR\rchecksumBytes\x12@\n" +
	"\rchecksum_type\x18\t \x01(\x0e2\x1b.splitandgo.v1.ChecksumTypeR\fchecksumType\x12\x17\n" +
	"\ais_last\x18\n" +
	" \x01(\bR\x06isLast\x12#\n" +
	"\ris_compressed\x18\v \x01(\bR\fisCompressed\x12F\n" +
	"\bmetadata\x18\f \x03(\v2*.splitandgo.v1.ChunkEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\tStreamAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fchunks_received\x18\x02 \x01(\x03R\x0echunksReceived\x12%\n" +
	"\x0ebytes_received\x18\x03 \x01(\x03R\rbytesReceived\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xf7\x01\n" +
	"\x15StreamDownloadRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x120\n" +
	"\x14preferred_chunk_size\x18\x02 \x01(\x05R\x12preferredChunkSize\x12N\n" +
	"\bmetadata\x18\x03 \x03(\v22.splitandgo.v1.StreamDownloadRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*x\n" +
	"\fChecksumType\x12\x1d\n" +
	"\x19CHECKSUM_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHECKSUM_TYPE_NONE\x10\x01\x12\x17\n" +
	"\x13CHECKSUM_TYPE_CRC32\x10\x02\x12\x18\n" +
	"\x14CHECKSUM_TYPE_SHA256\x10\x032\xff\x01\n" +
	"\rStreamService\x12H\n" +
	"\fStreamUpload\x12\x1c.splitandgo.v1.ChunkEnvelope\x1a\x18.splitandgo.v1.StreamAck(\x01\x12V\n" +
	"\x0eStreamDownload\x12$.splitandgo.v1.StreamDownloadRequest\x1a\x1c.splitandgo.v1.ChunkEnvelope0\x01\x12L\n" +
	"\n" +
	"StreamBidi\x12\x1c.splitandgo.v1.ChunkEnvelope\x1a\x1c.splitandgo.v1.ChunkEnvelope(\x010\x01B:Z8github.com/vimoksh/split-and-go/pkg/transport/grpc/pb;pbb\x06proto3"

var (
	file_splitandgo_v1_chunk_proto_rawDescOnce sync.Once
	file_splitandgo_v1_chunk_proto_rawDescData []byte
)

func file_splitandgo_v1_chunk_proto_rawDescGZIP() []byte {
	file_splitandgo_v1_chunk_proto_rawDescOnce.Do(func() {
		file_splitandgo_v1_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_splitandgo_v1_chunk_proto_rawDesc), len(file_splitandgo_v1_chunk_proto_rawDesc)))
	})
	return file_splitandgo_v1_chunk_proto_rawDescData
}

var file_splitandgo_v1_chunk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_splitandgo_v1_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_splitandgo_v1_chunk_proto_goTypes = []any{
	(ChecksumType)(0),             // 0: splitandgo.v1.ChecksumType
	(*ChunkEnvelope)(nil),         // 1: splitandgo.v1.ChunkEnvelope
	(*StreamAck)(nil),             // 2: splitandgo.v1.StreamAck
	(*StreamDownloadRequest)(nil), // 3: splitandgo.v1.StreamDownloadRequest
	nil,                           // 4: splitandgo.v1.ChunkEnvelope.MetadataEntry
	nil,                           // 5: splitandgo.v1.StreamDownloadRequest.MetadataEntry
}
var file_splitandgo_v1_chunk_proto_depIdxs = []int32{
	0, // 0: splitandgo.v1.ChunkEnvelope.checksum_type:type_name -> splitandgo.v1.ChecksumType
	4, // 1: splitandgo.v1.ChunkEnvelope.metadata:type_name -> splitandgo.v1.ChunkEnvelope.MetadataEntry
	5, // 2: splitandgo.v1.StreamDownloadRequest.metadata:type_name -> splitandgo.v1.StreamDownloadRequest.MetadataEntry
	1, // 3: splitandgo.v1.StreamService.StreamUpload:input_type -> splitandgo.v1.ChunkEnvelope
	3, // 4: splitandgo.v1.StreamService.StreamDownload:input_type -> splitandgo.v1.StreamDownloadRequest
	1, // 5: splitandgo.v1.StreamService.StreamBidi:input_type -> splitandgo.v1.ChunkEnvelope
	2, // 6: splitandgo.v1.StreamService.StreamUpload:output_type -> splitandgo.v1.StreamAck
	1, // 7: splitandgo.v1.StreamService.StreamDownload:output_type -> splitandgo.v1.ChunkEnvelope
	1, // 8: splitandgo.v1.StreamService.StreamBidi:output_type -> splitandgo.v1.ChunkEnvelope
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_splitandgo_v1_chunk_proto_init() }
func file_splitandgo_v1_chunk_proto_init() {
	if File_splitandgo_v1_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_splitandgo_v1_chunk_proto_rawDesc), len(file_splitandgo_v1_chunk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_splitandgo_v1_chunk_proto_goTypes,
		DependencyIndexes: file_splitandgo_v1_chunk_proto_depIdxs,
		EnumInfos:         file_splitandgo_v1_chunk_proto_enumTypes,
		MessageInfos:      file_splitandgo_v1_chunk_proto_msgTypes,
	}.Build()
	File_splitandgo_v1_chunk_proto = out.File
	file_splitandgo_v1_chunk_proto_goTypes = nil
	file_splitandgo_v1_chunk_proto_depIdxs = nil
}
